chore(build): fix broken build due to insecure commands
Fix broken build:
```
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`.
```

see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Hence, we updated the version of the plugin `action/setup-node` to the latest available one.